apiVersion: v1
kind: Service
metadata:
  name: apache-service  # Updated service name for Apache
spec:
  type: NodePort
  selector:
    app: apache2  # Updated selector to match Apache pods
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010  # External access port
